# K Nearest Neighbors classification


This is already a classified data! We will see the how preprocessing of the data has been done(like getting dummies for catagorical values, imputations,handling missing values and various other preprocessing techniques)in another python session
They've hidden the feature column names but have given you the data and the target classes. 

We'll try to use KNN to create a model that directly predicts a class for a new data point based off of the features.

## Import Libraries



In [29]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
%matplotlib inline

## Get the Data

Set index_col=0 to use the first column as the index.

In [5]:
df = pd.read_csv("Classified Data",index_col=0)


In [6]:
df.head()

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608  0.759697   
1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450  0.675334   
2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781  1.626351   
3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128  1.409708   
4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727  1.115596   

        PJF       HQE       NXJ  TARGET CLASS  
0  0.643798  0.879422  1.231409             1  
1  1.013546  0.621552  1.492702             0  
2  1.154483  0.957877  1.285597             0  
3  1.380003  1.522692  1.153093             1  
4  0.646691  1.463812  1.419167             1

In [13]:
X=df.drop('TARGET CLASS',axis=1)
y=df['TARGET CLASS']

## Train Test Split
Trainig the data from the labelled data

In [14]:

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)

## Using KNN

Remember that we are trying to come up with a model to predict whether someone will TARGET CLASS or not. We'll start with k=1.

In [15]:
knn = KNeighborsClassifier(n_neighbors=1)

In [16]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [17]:
pred = knn.predict(X_test)
print(pred)

[1 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 1 1 0 1 0 0
 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 0
 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 1
 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1
 0 1 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1
 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 1 0 1 0
 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 1 0 1 1 1 0 1
 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 1 1 1
 0 1 0 1]


In [19]:
print(knn.score(X_test,y_test))

0.8966666666666666


## Predictions and Evaluations

Let's evaluate our KNN model!
We can evalvate the accuracy through cross validation as given below and we can distinguish the resulted accuracy how far it is 
difference between the mean of the below values.
provided the fold (cv=5) 

In [22]:
from sklearn.model_selection import cross_val_score
cv_results = cross_val_score(knn,X,y,cv=5)
print(cv_results)
np.mean(cv_results)

[0.905 0.9   0.89  0.93  0.94 ]


0.913

Evaluation using confusion matrix: Which will provide the True-Positive and false-Negative predictions of the result 
as part of accuracy and precision values 

In [55]:
print(confusion_matrix(y_test,pred))

[[130  15]
 [ 12 143]]


In [49]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.94      0.87      0.90       150
           1       0.88      0.94      0.91       150

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



## Choosing a K Value : Tuning the Hyper parameter

Let's go ahead and use the elbow method to pick a good K Value:

Using for loop over a cretain range of k values, we can determine the suitable k value for our model 
at the lowest error value by plotting matplotlib

In [37]:
error_rate = []

# Will take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

Now we will plot between the error rate and k value ranging from 1 to 40

plt.figure(figsize=(10,6))
plt.plot(range(1,40),error_rate,color='blue', linestyle=None, marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

Here we can see that that after arounds K>23 the error rate just tends to hover around 0.06-0.05 Let's retrain the model with that and check the classification report!

In [100]:
# FIRST A QUICK COMPARISON TO OUR ORIGINAL K=1
knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train,y_train)
pred = knn.predict(X_test)

print('WITH K=1')
print('\n')
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

WITH K=1


[[125  18]
 [ 13 144]]


             precision    recall  f1-score   support

          0       0.91      0.87      0.89       143
          1       0.89      0.92      0.90       157

avg / total       0.90      0.90      0.90       300



In [23]:
# NOW WITH K=23
knn = KNeighborsClassifier(n_neighbors=23)

knn.fit(X_train,y_train)
pred = knn.predict(X_test)

print('WITH K=23')
print('\n')
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

WITH K=23


[[131  14]
 [  4 151]]


              precision    recall  f1-score   support

           0       0.97      0.90      0.94       145
           1       0.92      0.97      0.94       155

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



Hyper parameter Tuning through GridSearchCv :
Let's see how we can select the parameter using GridSearchCV 

In [34]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors':np.arange(1,40)}
knn=KNeighborsClassifier()
cv_result2 = GridSearchCV(knn,param_grid,cv=5)
cv_result2.fit(X_train,y_train)
cv_result2.best_params_

{'n_neighbors': 20}

We have determined the k value as 20 using GridSearchCV
This Search involves the cross validation at each and every k value from range(1,40)
let's also see the accuracy value at k=20

In [36]:
cv_result2.best_score_

0.9442857142857143

In [ ]:
We can also use RandomSearchCV when we have more parameter space,In which we will be selecting the parameters randomly to 
save the computational time 